account/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views



urlpatterns = [
    #path('login/', views.user_login, name='login'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
    path('', views.dashboard, name='dashboard'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/change_pass_form.html'), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/change_pass_done.html'), name='password_change_done'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/reset_pass_form.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/reset_pass_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/reset_pass_confirm.html'), name='password_reset_confirm'),
    path('reset/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/reset_pass_complete.html'), name='password_reset_complete'),
    path('register/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('user/', views.user_list, name='user_list'),
    path('user/followers/', views.followers_list, name='followers_list'),
    path('user/followed/', views.followed_list, name='followed_list'),
    path('user/search_user/', views.search_user, name='search_user'),
    path('user/follow/', views.user_follow, name='user_follow'),
    path('user/<username>/', views.user_detail, name='user_detail'),
]

bookmarks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('account/', include('account.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('images/', include('images.urls', namespace='images')),
    path('chat/', include('chat.urls', namespace='chat')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.messages_page, name='messages_page'),
    path('createth/<username>/', views.create_thread, name='create_thread'),
    path('detail_usr/', views.detail_usr, name='detail_usr'),
]

images/urls.py
from django.urls import path
from . import views


app_name = 'images'


urlpatterns = [
    path('create/', views.image_create, name='create'),
    path('edit/<id>/', views.image_edit, name='edit'),
    path('detail/<int:id>/<slug:slug>/', views.image_detail, name='detail'),
    path('like/', views.image_like, name='like'),
    path('', views.image_list, name='list'),
    path('ranking/', views.image_ranking, name='ranking'),
    path('option_image/', views.option_image, name='option_image'),
    
]

account/models.py
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    date_of_brith = models.DateField(blank=True, null=True)
    photo = models.ImageField(upload_to='users/%Y/%m/%d/', blank=False, default='users/user_logo_default.png')
    
    def __str__(self):
        return 'Profile for user {}'.format(self.user.username)

class Contact(models.Model):
    user_from = models.ForeignKey('auth.User', related_name='rel_from_set', on_delete=models.CASCADE)
    user_to = models.ForeignKey('auth.User', related_name='rel_to_set', on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True, db_index=True)

    class Meta:
        ordering = ['-created']
    
    def __str__(self):
        return '{} follows {}'.format(self.user_from, self.user_to)

# Adaugarea dinamica a campului following in tabelul User din Django
User.add_to_class('following', models.ManyToManyField('self', through=Contact, related_name='followers', symmetrical=False))

account/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.password_validation import validate_password
from .models import Profile


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'Title':'test'}))
    password = forms.CharField(widget=forms.PasswordInput)

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')
    
    def clean(self):
        cd = self.cleaned_data
        
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Parola nu conincide.')

        if User.objects.filter(email=cd['email']).count() > 0:
            raise forms.ValidationError('Utilizator cu asa email deja exista.')

        validate_password(cd['password'], self.instance)
        
        return cd

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('date_of_brith', 'photo')

class SearchForm(forms.Form):
    search_query = forms.CharField(max_length=100)
    type_search = forms.CharField(max_length=10)

account/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, JsonResponse
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Max
from .forms import LoginForm, UserRegistrationForm, UserEditForm, ProfileEditForm, SearchForm
from .models import Profile, Contact
from django.contrib.auth.models import User
from django.db.models import Value as V
from django.db.models.functions import Concat
from django.views.decorators.http import require_POST
from bookmarks.common.decorators import ajax_required
from actions.utils import create_action
from actions.models import Action
from datetime import datetime, timedelta


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request,
                                username=cd['username'],
                                password=cd['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponse('Authenticated successfully')
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login or password')
    else:
        form = LoginForm()
    
    return render(request, 'account/login.html', {'form': form})


#@login_required
def dashboard(request):
    if request.user.is_authenticated:
        if request.user.profile.photo == '':
            redirect('edit')
        
        #actions = Action.objects.exclude(user=request.user)
        actions = Action.objects
        following_ids = request.user.following.values_list('id', flat=True)
        following_ids = following_ids.exclude(id=request.user.id)
        date_last_days = datetime.now().date() - timedelta(days=7)
        #print(date_last_days)

        query = f'''
            SELECT id, user_id, verb, target_ct_id, target_id, max(created)
            FROM actions_action
            WHERE user_id != '{request.user.id}'
            AND verb == 'is following'
            AND target_id = '{request.user.id}'
            AND created >= '{date_last_days}'
            GROUP BY user_id, verb, target_ct_id, target_id
            ORDER BY id desc, created desc
        '''
        new_followers = actions.raw(query)
 
        query = f'''
            SELECT id, user_id, verb, target_ct_id, target_id, max(created)
            FROM actions_action
            WHERE user_id != '{request.user.id}'
            AND verb != 'has created an account'
            AND user_id in ({",".join([str(x) for x in list(following_ids)])})
            GROUP BY user_id, verb, target_ct_id, target_id
            ORDER BY created desc
        '''
        actions = actions.raw(query)
        actions.new_followers = [user_id.id for user_id in new_followers]

        '''if following_ids:
            actions = actions.filter(user_id__in=following_ids)
        else:
            actions = actions.select_related('user', 'user__profile')\
                        .prefetch_related('target')'''


        return render(request, 'account/dashboard.html', {'section':'dashboard', 'actions':actions, 'new_followers':new_followers})
    else:
        return render(request, 'welcPage.html')


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            Profile.objects.create(user=new_user)
            create_action(new_user, 'has created an account')
            return render(request, 'account/register_done.html', {'new_user':new_user})
    else:
        user_form = UserRegistrationForm()
        
    return render(request, 'account/register.html', {'user_form':user_form})

@login_required
def edit(request):
    message_status = ''
    if request.method == 'POST':
        user_form = UserEditForm(instance=request.user, data=request.POST)
        profile_form = ProfileEditForm(instance=request.user.profile, data=request.POST, files=request.FILES)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            #messages.success(request, 'Profile updated successfully')
            message_status = "Profilul a fost modificat cu success"
        else:
            #messages.error(request, 'Error updating your profile')
            message_status = "Eroare la modificarea profilului"
        
        user_form = request.user
        profile_form = request.user.profile
        profile_form.date_of_birth_mod = datetime.strftime(datetime.strptime(str(profile_form.date_of_brith), "%Y-%m-%d"), "%Y-%m-%d")
    else:
        user_form = request.user
        profile_form = request.user.profile
        profile_form.date_of_birth_mod = datetime.strftime(datetime.strptime(str(profile_form.date_of_brith), "%Y-%m-%d"), "%Y-%m-%d")
    
    return render(request, 'account/edit.html', {'user_form':user_form, 'profile_form':profile_form, 'message_status':message_status})

@login_required
def user_list(request):
    users = User.objects.filter(is_active=True)
    return render(request, 'account/user/list.html', {'section':'people', 'users':users, 'filt':'all'})

@login_required
def followers_list(request):
    abonati = Contact.objects.filter(user_to=request.user)
    users = [user.user_from for user in abonati]
    return render(request,'account/user/list.html', {'section':'people', 'users':users, 'filt':'follow'})

@login_required
def followed_list(request):
    abonati = Contact.objects.filter(user_from=request.user)
    users = [user.user_to for user in abonati]
    return render(request,'account/user/list.html', {'section':'people', 'users':users, 'filt':'folled'})

@login_required
def user_detail(request, username):
    user = get_object_or_404(User, username=username, is_active=True)
    
    user.abonari = Contact.objects.filter(user_from=user).count()

    query = f'''
        SELECT id, user_id, verb, target_ct_id, target_id, max(created)
        FROM actions_action
        WHERE user_id = '{user.id}'
        AND verb != 'has created an account'
        GROUP BY user_id, verb, target_ct_id, target_id
        ORDER BY created desc
    '''
    user.actions_user = Action.objects.raw(query)
    #print(user.profile.date_of_brith)
    #print((datetime.now() - datetime.strptime(str(user.profile.date_of_brith), "%Y-%d-%m")).days)
    try:
        user.age_result = (datetime.now() - datetime.strptime(str(user.profile.date_of_brith), "%Y-%m-%d")).days // 365
    except:
        user.age_result = "-"


    return render(request, 'account/user/detail.html', {'section':'people', 'user':user})


@ajax_required
@require_POST
@login_required
def user_follow(request):
    user_id = request.POST.get('id')
    action = request.POST.get('action')
    
    if user_id and action:
        try:
            user = User.objects.get(id=user_id)
            
            if action == 'follow':
                Contact.objects.get_or_create(user_from=request.user, user_to=user)
                create_action(request.user, 'is following', user)
            else:
                Contact.objects.filter(user_from=request.user, user_to=user).delete()

            return JsonResponse({'status':'ok'})
        except User.DoesNotExist:
            return JsonResponse({'status':'ok'})
    
    return JsonResponse({'status':'ok'})

@login_required
def search_user1(request):
    users = request.POST.get('users')
    filt = request.POST.get('filt')
    
    search_value = request.POST.get('search_value')
    if filt != "all":
        abonati = Contact.objects.filter(user_from=request.user)
        users = [user.user_to for user in abonati]
        users = [user for user in users if str(user.get_full_name()).lower().__contains__(str(search_value).lower())]
    else:
        users = User.objects.annotate(full_name=Concat('first_name', V(' '), 'last_name')).filter(full_name__icontains=search_value)
    #print(users)
    #context = {'section':'people', 'users': users, 'filt':filt}
    return render(request, 'account/user/list.html', {'section':'people', 'users': users, 'filt':filt})


@login_required
def search_user(request):
    form = SearchForm(request.POST)
    if form.is_valid():
        search_value = form.cleaned_data['search_query']
        filt = form.cleaned_data['type_search']
        print("Search value:", str(search_value).strip(), "Filt:", filt)
        if filt != "all":
            if filt == "follow":
                abonati = Contact.objects.filter(user_to=request.user)
                users_list = [user.user_from for user in abonati]
            else:
                abonati = Contact.objects.filter(user_from=request.user)
                users_list = [user.user_to for user in abonati]

            if str(search_value).strip() != '':
                users = [user for user in users_list if str(user.get_full_name()).lower().__contains__(str(search_value).lower())]
            else:
                users = users_list
        else:
            if str(search_value).strip() != '':
                users = User.objects.annotate(full_name=Concat('first_name', V(' '), 'last_name')).filter(full_name__icontains=search_value)
            else:
                users = User.objects.filter(is_active=True)

        return render(request, 'account/user/list.html', {'section':'people', 'users': users, 'filt':filt, 'srch_val':search_value})

    context = {'form': form, 'users': None, 'filt':'all'}

    
    return render(request, 'account/user/list.html', context)

account/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
    

    <title>{% block title %}{% endblock %} | SOCIOMEET</title>

    <!-- Bootstrap core CSS -->
    

    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"/>
    <link href="{% static "assets/css/fontawesome.css" %}" rel="stylesheet">
    <link href="{% static "assets/css/templatemo-space-dynamic.css" %}" rel="stylesheet">
    <link href="{% static "assets/css/animated.css" %}" rel="stylesheet">
    <link href="{% static "assets/css/owl.css" %}" rel="stylesheet">
    
    <link href="{% static "css/style_dash.css" %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">
		<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/messages.css' %}">

  </head>

<body>
  

  <!-- ***** Preloader Start ***** -->
  <div id="js-preloader" class="js-preloader">
    <div class="preloader-inner">
      <span class="dot"></span>
      <div class="dots">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>
  </div>
  <!-- ***** Preloader End ***** -->

  <!-- ***** Header Area Start ***** -->
  <header class="header-area header-sticky wow slideInDown" data-wow-duration="0.75s" data-wow-delay="0s">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <nav class="main-nav">
            <!-- ***** Logo Start ***** -->
            <a href="{% url "dashboard" %}" class="logo">
              <h4>Socio<span>Meet</span></h4>
            </a>
            <!-- ***** Logo End ***** -->
            <!-- ***** Menu Start ***** -->
            <ul class="nav">
                {% if request.user.is_authenticated %}
                    <li class="scroll-to-section">
                      <a {% if section == "dashboard" %}class="active"{% endif %} href="{% url "dashboard" %}">Acasă</a>
                    </li>
                    <li class="scroll-to-section">
                      <a {% if section == "images" %}class="active"{% endif %} href="{% url "images:list" %}">Imagini</a>
                    </li>
                    <li class="scroll-to-section">
                      <a {% if section == "people" %}class="active"{% endif %} href="{% url "user_list" %}">Utilizatori</a>
                    </li>
                    <li class="scroll-to-section">
                      <a {% if section == "chat" %}class="active"{% endif %} href="{% url "chat:messages_page" %}">Mesaje</a>
                    </li>
                {% endif %}
                <li class="scroll-to-section">
                    <div class="main-red-button">
                        {% if request.user.is_authenticated %}
                            <a href="{% url "logout" %}">Deconectare</a>
                        {% else %}
                            <a href="{% url "login" %}">Conectează-te</a>
                        {% endif %}
                    </div>
                </li> 
            </ul>        
            <a class='menu-trigger'>
                <span>Menu</span>
            </a>
            <!-- ***** Menu End ***** -->
          </nav>
        </div>
      </div>
    </div>
  </header>
  <!-- ***** Header Area End ***** -->

  {% block content %}
  {% endblock %}
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-12 wow fadeIn" data-wow-duration="1s" data-wow-delay="0.25s">
          <p>© Copyright 2023 SOCIOMEET. 
        </div>
      </div>
    </div>
  </footer>
  <!-- Scripts -->
  
  <script src="{% static "jquery/jquery.min.js" %}"></script>
  
  <script src="{% static "assets/js/owl-carousel.js" %}"></script>
  <script src="{% static "assets/js/animation.js" %}"></script>
  <script src="{% static "assets/js/imagesloaded.js" %}"></script>
  <script src="{% static "assets/js/templatemo-custom.js" %}"></script>
  <script src="{% static "js/myjs.js" %}"></script>
  <script src="{% static 'js/messages.js' %}"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
  <script>
    var csrftoken = Cookies.get('csrftoken');
    function csrfSafeMethod(method) {
      // these HTTP methods do not require CSRF protection
      return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    $.ajaxSetup({
      beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
          xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
      }
    });
    $(document).ready(function(){
      {% block domready %}
      {% endblock %}
       });
  </script>
</body>
</html>

account/templates/welcPage.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Bun venit {% endblock %}
{% block content %}
  <div class="main-banner wow fadeIn" id="top" data-wow-duration="1s" data-wow-delay="0.5s">
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <div class="row">
            <div class="col-lg-6 align-self-center">
              <div class="left-content header-text wow fadeInLeft" data-wow-duration="1s" data-wow-delay="1s">
                <h6>Bine ați venit pe Sociomeet</h6>
                <h2>Suntem bucuroși să vă avem alături în această comunitate <em>vibrantă</em> și <span>plină de viață</span></h2>
                <form id="search">
                  <fieldset>
                    <input type="address" name="address" class="email" placeholder="Niciun profil în SOCIOMEET" autocomplete="off" disabled required>
                  </fieldset>
                  <fieldset>
                    <a href="{% url "register" %}" class="main-button">Înregistrează-te</a>
                  </fieldset>
                </form>
              </div>
            </div>
            <div class="col-lg-6">
              <div class="right-image wow fadeInRight" data-wow-duration="1s" data-wow-delay="0.5s">
                <img src="{% static 'assets/images/about-left-image.png' %}" alt="person graphic" style="height: 383px; width: 331px; margin-left: 30%;">
                
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endblock %}