bookmarks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('account/', include('account.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('images/', include('images.urls', namespace='images')),
    path('chat/', include('chat.urls', namespace='chat')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.messages_page, name='messages_page'),
    path('createth/<username>/', views.create_thread, name='create_thread'),
    path('detail_usr/', views.detail_usr, name='detail_usr'),
]

images/urls.py
from django.urls import path
from . import views


app_name = 'images'


urlpatterns = [
    path('create/', views.image_create, name='create'),
    path('edit/<id>/', views.image_edit, name='edit'),
    path('detail/<int:id>/<slug:slug>/', views.image_detail, name='detail'),
    path('like/', views.image_like, name='like'),
    path('', views.image_list, name='list'),
    path('ranking/', views.image_ranking, name='ranking'),
    path('option_image/', views.option_image, name='option_image'),
    
]

images/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.urls import reverse


class Image(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='images_created', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, blank=True)
    url = models.URLField()
    image = models.ImageField(upload_to='image/%Y/%m/%d/')
    description = models.TextField(blank=True)
    created = models.DateField(auto_now_add=True, db_index=True)
    users_likes = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='images_liked', blank=True)
    total_likes = models.PositiveIntegerField(db_index=True, default=0)
    visibility = models.CharField(max_length=10, default="for_all")

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Image, self).save(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse('images:detail', args=[self.id, self.slug])

images/forms.py
from django import forms
from .models import Image
from urllib import request
from django.core.files.base import ContentFile
from django.utils.text import slugify


"""class ImageCreateForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('title', 'url', 'description')
        widgets = {'url': forms.HiddenInput, }
    
    def clean_url(self):
        url = self.cleaned_data['url']
        valid_extensions = ['jpg', 'jpeg']
        extension = str(url).rsplit('.', 1)[1].lower()

        if extension not in valid_extensions:
            raise forms.ValidationError('The given URL does not match valid image extensions.')
        
        return url
    
    def save(self, force_insert=False, force_update=False, commit=True):
        image = super(ImageCreateForm, self).save(commit=False)
        image_url = self.cleaned_data['url']
        image_name = '{}.{}'.format(slugify(image.title), image_url.rsplit('.', 1)[1].lower())

        response = request.urlopen(image_url)
        image.image.save(image_name, ContentFile(response.read()), save=False)

        if commit:
            image.save()
        return image"""
        
class ImageCreateForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('title', 'image', 'description')

class ImageUpdateForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('title', 'description', 'visibility')

images/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import ImageCreateForm, ImageUpdateForm
from .models import Image
from django.http import JsonResponse, HttpResponse
from django.views.decorators.http import require_POST
from bookmarks.common.decorators import ajax_required, is_ajax
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from actions.utils import create_action
from django.conf import settings
import redis

r = redis.StrictRedis(host=settings.REDIS_HOST, port=settings.REDIS_PORT, db=settings.REDIS_DB, password=settings.REDIS_PASSWORD)

def get_views_image(images):
    for ind, image in enumerate(images):
        try:
            images[ind].views = int(r.get(f"image:{str(image.id)}:views"))
        except:
            images[ind].views = 0
    
    return images


@login_required
def image_create(request):
    if request.method == 'POST':
        #form = ImageCreateForm(data=request.POST)
        form = ImageCreateForm(request.POST, request.FILES)
        print('img cr')

        if form.is_valid():
            print('valid')
            cd = form.cleaned_data
            new_item = form.save(commit=False)
            new_item.user = request.user
            new_item.save()
            create_action(request.user, 'bookmarked image', new_item)

            return redirect(new_item.get_absolute_url())
    else:
        form = ImageCreateForm(data=request.GET)
        
    return render(request, 'images/image/create.html', {'section':'images', 'form':form})

def image_detail(request, id, slug):
    image = get_object_or_404(Image, id=id, slug=slug)

    #print("Image visibility", image.visibility )
    if image.visibility == "for_non":
        return redirect('dashboard')

    total_views = r.incr('image:{}:views'.format(image.id))
    r.zincrby('image_ranking', image.id, 1)

    return render(request, 'images/image/detail.html', {'section':'images', 'image':image, 'total_views':total_views})

@ajax_required
@login_required
@require_POST
def image_like(request):
    image_id = request.POST.get('id')
    print(image_id)
    action = request.POST.get('action')
    print(action)

    if image_id and action:
        try:
            image = Image.objects.get(id=image_id)
            if action == 'like':
                image.users_likes.add(request.user)
                create_action(request.user, 'likes', image)
            else:
                image.users_likes.remove(request.user)
            
            total_likes = image.users_likes.count()
            return JsonResponse({'status':'ok', 'image_id':image_id, 'action':action, 'total_likes':total_likes})
        except:
            pass
    return JsonResponse({'status':'ok', 'image_id': image_id, 'action':action, 'total_likes':0})

@login_required
def image_list(request):
    images = Image.objects.filter(visibility__in=["for_all", "for_fol"])
    paginator = Paginator(images, 8)
    page = request.GET.get('page')

    try:
        images = paginator.page(page)
    except PageNotAnInteger:
        # Daca prima pagina nu este numar returnam prima pagina 
        image = paginator.page(1)
    except EmptyPage:
        if is_ajax(request=request):
            # Daca primi AJAX-request cu numarul de pagini mai mare dechit totalul paginilor
            # returnam pagina goala
            return HttpResponse('')
        images = paginator.page(paginator.num_pages)

    images = get_views_image(images)
    #images = images.order_by("views")
    images = sorted(images, key= lambda t: t.views, reverse=True)
    #print(images_test)
    if is_ajax(request=request):
        return render(request, 'images/image/list_ajax.html', {'section':'images', 'images':images})
    
    return render(request, 'images/image/list.html', {'section':'images', 'images':images})


@login_required
def image_ranking(request):
    image_ranking = r.zrange('image_ranking', 0, -1, desc=True)[:10]
    image_ranking_ids = [int(id) for id in image_ranking]
    most_viewed = list(Image.objects.filter(id__in=image_ranking_ids))
    most_viewed.sort(key=lambda x: image_ranking_ids.index(x.id))
    return render(request, 'images/image/ranking.html', {'section':'images', 'most_viewed':most_viewed})

@ajax_required
@login_required
@require_POST
def option_image(request):
    option = request.POST.get('option')
    image_id = request.POST.get('id')

    if option == "visibility":
        value = request.POST.get('value')
        Image.objects.filter(id=image_id).update(visibility=value)
    elif option == "delete_feed":
        Image.objects.filter(id=image_id).update(visibility='for_non')

    return JsonResponse({'status':'ok'})

@login_required
def image_edit(request, id=None):
    message_status = ''
    if request.method == 'POST':
        image_id = request.POST.get('image_id')
        title = request.POST.get('title')
        description = request.POST.get('description')
        visibility = request.POST.get('visibility')
        slug = request.POST.get('slug')

        if image_id != None:
            #image_form.save()
            Image.objects.filter(id=image_id).update(title=title, description=description, visibility=visibility)
            #message_status = "Postarea a fost modificat cu success"
            return redirect("images:detail", id=id, slug=slug)
        else:
            #messages.error(request, 'Error updating your profile')
            message_status = "Eroare la modificarea postării"
            print("Eroare la modificarea postării")
            #messages.error(request, 'Eroare la modificarea postării')
            image_form = Image.objects.filter(id=id)[0]

    else:
        image_form = Image.objects.filter(id=id)[0]
        #profile_form.date_of_birth_mod = datetime.strftime(datetime.strptime(str(profile_form.date_of_brith), "%Y-%m-%d"), "%Y-%m-%d")
    
    return render(request, 'images/image/edit.html', {'image_form':image_form, 'message_status':message_status})

images/templates/images/image/create.html
{% extends "base.html" %}
{% load static %}
{% block title %}Încarcă imaginea{% endblock %}
{% block content %}
<div id="services" class="our-services section">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 align-self-center  wow fadeInLeft" data-wow-duration="1s" data-wow-delay="0.2s">
          <div class="left-image">
            <img src="#" id="blah" alt="your image" style = "display: none;">
            <!--style = "display: none;"-->
          </div>
        </div>
        <div class="col-lg-6 wow fadeInRight" data-wow-duration="1s" data-wow-delay="0.2s">
            <div class="section-heading">
                <h2>Postare nouă</h2>
            </div>
            <div class="photo">
            
            </div>

            <form action="." method="post" enctype="multipart/form-data">
                <div class="form-group">
                    <label for="input-title">Titlul postării</label>
                    <input type="text" class="form-control" id="input-title" name="title" required>
                </div>
                <div class="form-group">
                    <label for="input-descriere">Descriere</label>
                    <textarea class="form-control" name="description" spellcheck="false" rows="7" cols="50" required></textarea>
                </div>
                <div class="form-group">
                    <label for="control-select">Vizibilitate</label>
                    <select class="form-control" id="control-select" name="visibility">
                        <option value="for_me">Doar pentru mine</option>
                        <option value="for_followers">Pentru abonați</option>
                        <option value="for_all">Pentru toți</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="input-file">Selectează fisierul</label>
                    <input type="file" class="form-control-file" id="input-file" placeholder="Titlul postării" name="image" onchange="readURL(this);" required>
                </div>
                <div class="form-group">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger" required>Postează</button>
                </div>
            </form>
        </div>
      </div>
    </div>
</div>

<script>
    const container = document.querySelector(".container"),
    privacy = container.querySelector(".post .privacy"),
    arrowBack = container.querySelector(".audience .arrow-back");
    const boxPostModal = document.querySelector('.create-box-g .blah');

    boxPostModal.addEventListener("click", () => {
        document.getElementById("imageUpld").value = "";
        $('#blah').attr('src', "#");
        boxPostModal.style.display = 'none';
    });

    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#blah').attr('src', e.target.result);
                $('#blah').attr('style', "display: static;");
                //boxPostModal.style.display = 'grid';
            };

            reader.readAsDataURL(input.files[0]);
            
        }
    }
    </script>
{% endblock %}

images/templates/images/image/detail.html
{% extends "base.html" %}
{% block title %}{{ image.title }}{% endblock %}
{% block content %}

<div id="services" class="our-services section">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 align-self-center  wow fadeInLeft" data-wow-duration="1s" data-wow-delay="0.2s">
          <div class="left-image">
            <img src="{{image.image.url}}" alt="">
          </div>
        </div>
        <div class="col-lg-6 wow fadeInRight" data-wow-duration="1s" data-wow-delay="0.2s">
          <div class="section-heading">
            <h2>{{ image.title }}</h2>
            <small><a href="{{image.user.get_absolute_url}}">{{image.user.get_full_name}}</a></small>
            <br>
            <small>{{image.created}}</small>
            <p>{{ image.description }}</p>
          </div>
          <div class="row">
            <div class="col-lg-12">
              <div class="first-bar progress-skill-bar">
                <h4>Detalii</h4>
                <div class="detail-image">
                  <li>{{total_views}} vizionări</li>
                  <li class="number-likes">
                    <a href="" data-id="{{ image.id }}" 
                      data-action="{% if request.user in image.users_likes.all %}un{% endif %}like"
                      class="like button" id="like-act">
                      <i id="like-icon" class="fa-{% if request.user in image.users_likes.all %}solid{% else %}regular{% endif %} fa-heart"></i>
                    </a> 
                    <button type="button" id="button-total-like" class="btn btn-primary total" data-toggle="modal" data-target="#exampleModalScrollable" >
                      {{image.total_likes}}
                    </button>
                    
                  </li>
                </div>
              </div>
            </div>
            {% if request.user == image.user %}
              <div class="col-lg-12">
                <div class="first-bar progress-skill-bar">
                  <h4>Setări</h4>
                  <label>Vizibilitate:</label>
                  <select  name="visibility" id="visibility" data-id="{{ image.id }}" >
                    <option value="for_mee" {% if image.visibility == 'for_mee' %} selected {% endif %}>Doar pentru mine</option>
                    <option value="for_fol" {% if image.visibility == 'for_fol' %} selected {% endif %}>Pentru abonați</option>
                    <option value="for_all" {% if image.visibility == 'for_all' %} selected {% endif %}>Pentru toți</option>
                  </select>
                </div>
                <form action="{% url 'images:edit' image.id %}">
                  <button type="submit" class="btn btn-info">Editează postarea</button>
                </form>
                <br>
                <button type="submit" class="btn btn-danger" data-toggle="modal" data-target="#areyousure" >Sterge postarea</button>
              </div>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
</div>



<!-- Modal -->
<div class="modal fade" id="exampleModalScrollable" tabindex="-1" role="dialog" aria-labelledby="exampleModalScrollableTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalScrollableTitle">Utilizatorii care le-au plăcut imaginea.</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="list-group">
          {% for user in image.users_likes.all %}
            <a href="{{user.get_absolute_url}}" class="list-group-item list-group-item-action">
              {{user.get_full_name}}
            </a>
          {% endfor %}
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<!-- Modal 2 -->
<div class="modal fade" id="areyousure" tabindex="-1" role="dialog" aria-labelledby="exampleModalScrollableTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalScrollableTitle">Sterge postarea</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="list-group">
          Sunte-ți sigur de acțiunea accesată?
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Nu</button>
        <button type="button" class="btn btn-danger" id="button-delete-feed" data-dismiss="modal" data-id="{{image.id}}">Da</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}
{% block domready %}
$('button#button-delete-feed').click(function(e){
  e.preventDefault();
  $.post(
      '{% url "images:option_image" %}',
      {id: $(this).data('id'),option: 'delete_feed'},
      function(data){
        if (data['status'] == 'ok'){
          window.location.replace('{% url "user_detail" username=request.user.username %}');
      }
      }
  );
  });

$('select#visibility').on('change', function(e) {
    e.preventDefault();
    $.post(
        '{% url "images:option_image" %}',
        {id: $(this).data('id'),option:'visibility', value: this.value},
        function(data){
          if (data['status'] == 'ok'){
            console.log("ok_select");
        }
        }
    );
});

 $('a.like').click(function(e){
    e.preventDefault();
    $.post(
        '{% url "images:like" %}',
        {id: $(this).data('id'),action: $(this).data('action')},
        function(data){
          if (data['status'] == 'ok'){
            var previous_action = data['action'];
            var id_image = data['image_id'];

            $('a#like-act').data('action', previous_action == 'like' ?'unlike' : 'like');
            console.log(previous_action);
            if (previous_action == 'like'){
              
                $('i#like-icon').removeClass('fa-regular fa-heart');
                $('i#like-icon').addClass('fa-solid fa-heart');
            }
            else{
                $('i#like-icon').removeClass('fa-solid fa-heart');
                $('i#like-icon').addClass('fa-regular fa-heart');
            }
            var previous_likes = parseInt(data['total_likes']);
            console.log(previous_likes);
            $('button#button-total-like').text(previous_likes);
        }
        }
    );
    });
{% endblock %}

images/templates/images/image/edit.html
{% extends "base.html" %}
{% load static %}
{% block title %}Editarea postării{% endblock %}
{% block content %}
<div id="services" class="our-services section">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 align-self-center  wow fadeInLeft" data-wow-duration="1s" data-wow-delay="0.2s">
          <div class="left-image">
            <img src="{{image_form.image.url}}" id="blah" alt="your image">
            <!--style = "display: none;"-->
          </div>
        </div>
        <div class="col-lg-6 wow fadeInRight" data-wow-duration="1s" data-wow-delay="0.2s">
            <div class="section-heading">
                <h2>Editarea postării</h2>
            </div>
            <div class="photo">
            
            </div>
            {% if message_status != '' %}
                <div class="col-lg-12">
                    <div class="alert alert-danger" role="alert">
                        {{message_status}}
                    </div>
                </div>
            {% endif %}

            <form action="." method="post" enctype="multipart/form-data">
                <div class="form-group">
                    <label for="input-title">Titlul postării</label>
                    <input type="text" value="{{image_form.title}}" class="form-control" id="input-title" name="title" required>
                </div>
                <div class="form-group">
                    <label for="input-descriere">Descriere</label>
                    <textarea class="form-control"  name="description" spellcheck="false" rows="7" cols="50" required>{{image_form.description}}</textarea>
                </div>
                <div class="form-group">
                    <label for="control-select">Vizibilitate</label>
                    <select class="form-control" id="control-select" name="visibility">
                        <option value="for_mee" {% if image_form.visibility == 'for_mee' %} selected {% endif %}>Doar pentru mine</option>
                        <option value="for_fol" {% if image_form.visibility == 'for_fol' %} selected {% endif %}>Pentru abonați</option>
                        <option value="for_all" {% if image_form.visibility == 'for_all' %} selected {% endif %}>Pentru toți</option>
                    </select>
                </div>
                <div class="form-group">
                    {% csrf_token %}
                    <input type="hidden"  id="input-file" name="image_id" value="{{image_form.id}}">
                    <input type="hidden"  id="input-file" name="slug" value="{{image_form.slug}}">
                    <button type="submit" class="btn btn-danger" required>Editează</button>
                </div>
            </form>
        </div>
      </div>
    </div>
</div>

<script>
    const container = document.querySelector(".container"),
    privacy = container.querySelector(".post .privacy"),
    arrowBack = container.querySelector(".audience .arrow-back");
    const boxPostModal = document.querySelector('.create-box-g .blah');

    boxPostModal.addEventListener("click", () => {
        document.getElementById("imageUpld").value = "";
        $('#blah').attr('src', "#");
        boxPostModal.style.display = 'none';
    });

    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#blah').attr('src', e.target.result);
                $('#blah').attr('style', "display: static;");
                //boxPostModal.style.display = 'grid';
            };

            reader.readAsDataURL(input.files[0]);
            
        }
    }
    </script>
{% endblock %}

images/templates/images/image/list.html
{% extends "base.html" %}
{% block title %}Images bookmarked{% endblock %}
{% block content %}
    <div class="container">
        <h1>Images bookmarked</h1>
        <div id="image-list">
            {% include "images/image/list_ajax.html" %}
        </div>
    </div>
{% endblock %}
{% block domready %}
    var page = 1;
    var empty_page = false;
    var block_request = false;
    $(window).scroll(function() {
        var margin = $(document).height() - $(window).height()-200;
        if ($(window).scrollTop() > margin && empty_page == false && block_request == false) {
            block_request = true;
            page += 1;
            $.get('?page=' + page, function(data) {
            if(data == '') {empty_page = true;}
            else {
                block_request = false;
                $('#image-list').append(data);
            }
            });
        }
    });
{% endblock %}

images/templates/images/image/list_ajax.html
{% load thumbnail %}
{% load images_tags %}
<div id="blog" class="our-blog section">
    <div class="container">
        <div class="section-heading wow fadeInDown">
            <h2>Imaginile <em>populare</em> încărcate de <span>utilizatori</span></h2>
        </div>
        <div class="row">
            {% for image in images %}
                {% if image.visibility != 'for_non' %}
                    <div class="col-lg-4 item wow fadeInUp" data-wow-duration="1s" data-wow-delay="0.25s">
                        <div class="left-image">
                            <a href="{{image.get_absolute_url}}"><img src="{{image.image.url}}" alt="Workspace Desktop"></a>
                            <div class="info">
                                <div class="inner-content">
                                    <a href="{{image.get_absolute_url}}"><h4>{{image.title}}</h4></a>
                                    <ul>
                                        <li><i class="fa fa-calendar"></i> {{image.created}}</li>
                                        <br>
                                        <li><i class="fa fa-user"></i> <a href="{{image.user.get_absolute_url}}">{{image.user.get_full_name}}</a></li>
                                        <hr>
                                        <li><i class="fa fa-eye"></i> {{image.views}}</li>
                                        <li><i class="fa fa-heart"></i> {{image.total_likes}}</li>

                                    </ul>
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>
    </div>
</div>

images/templates/images/image/ranking.html
{% extends "base.html" %}
{% block title %}Images ranking{% endblock %}
{% block content %}
    <h1>Images ranking</h1>
    <ol>
        {% for image in most_viewed %}
            <li>
                <a href="{{ image.get_absolute_url }}">{{ image.title }}</a>
            </li>
        {% endfor %}
    </ol>
{% endblock %}